# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c140c113dad22ded593e4442463ea9c56b2c4d4fbb19955d8bf87c34d4ae6903af2ffbc9bcd9fa4d22640c5680f90f54a4a739083d46244afd317ea702f2faf7

test:
  secret_key_base: bda975272aba19374d5898bd71603ea460634042b4f987d0982381ba51bd59b785da55ec34504439813f7d2da85e17775e18e8fcc85c69317c42503a1ace7d02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
